[build]
  command = "npm run build && cp public/*.txt .next/"
  publish = ".next"

# 静态文件处理
[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/plain"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# 静态文件处理
[[headers]]
  for = "/*.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/knowledge_tree/*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=86400"